export default [
  {
    id: 1,
    postedOn: new Date(),
    title: "Frontend Developer",
    type: "Full time",
    location: "Remote",
    companyName: "Google",
    companyUrl: "Google.com",
    skills: ["Javascript", "React.js", "Node.js"],
    salary: "12000$",
  },
  {
    id: 2,
    postedOn: new Date(),
    title: "Backend Developer",
    type: "Part time",
    location: "Office",
    companyName: "Yahoo",
    companyUrl: "Yahoo.com",
    skills: ["Angular", "Node.js"],
    salary: "15000$",
  },
  {
    id: 3,
    postedOn: new Date(),
    title: "Mobile dev",
    type: "Contract",
    location: "Remote",
    companyName: "Facebook",
    companyUrl: "https://facebook.com",
    skills: ["flutter"],
    salary: "20000$",
  },
];
